//PACIENTES

export const GET_PACIENTES = "GET_PACIENTES";
export const GET_PACIENTE = "GET_PACIENTE";
export const POST_PACIENTE = "POST_PACIENTE";
export const UPDATE_PACIENTE = "UPDATE_PACIENTE";
export const DELETE_PACIENTE = "DELETE_PACIENTE";
export const ERROR_PACIENTE = "ERROR_PACIENTE";

//DOCTORES

export const GET_DOCTORES = "GET_DOCTORES";
export const GET_DOCTOR = "GET_DOCTOR";
export const POST_DOCTOR = "POST_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const ERROR_DOCTOR = "ERROR_DOCTOR";

//ENFERMEROS

export const GET_ENFERMEROS = "GET_ENFERMEROS";
export const GET_ENFERMERO = "GET_ENFERMERO";
export const POST_ENFERMERO = "POST_ENFERMERO";
export const UPDATE_ENFERMERO = "UPDATE_ENFERMERO";
export const DELETE_ENFERMERO = "DELETE_ENFERMERO";
export const ERROR_ENFERMERO = "ERROR_ENFERMERO";

//DIAGNOSTICOS

export const GET_DIAGNOSTICOS = "GET_DIAGNOSTICOS";
export const GET_DIAGNOSTICO = "GET_DIAGNOSTICO";
export const POST_DIAGNOSTICO = "POST_DIAGNOSTICO";
export const UPDATE_DIAGNOSTICO = "UPDATE_DIAGNOSTICO";
export const DELETE_DIAGNOSTICO = "DELETE_DIAGNOSTICO";
export const ERROR_DIAGNOSTICO = "ERROR_DIAGNOSTICO";
export const START_DIAGNOSTICO = "START_DIAGNOSTICO";

//AUTH

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const LOGIN_START = "LOGINT_START";

//IA

export const IA_START = "IA_START";
export const IA_ERROR = "IA_ERROR";
export const IA_RESULT = "IA_RESULT";
export const IA_SUCCESS = "IA_SUCCESS";
